more vmctl features

diff --git a/vmctl b/vmctl
--- a/vmctl
+++ b/vmctl
@@ -43,11 +43,14 @@ Commands:
   delete-iso    Delete an ISO
   destroy       Destroy a VM and its dataset
   download-iso  Download an ISO
+  edit          Edit a VM's configuration
   init          Initialize the bhyve dataset
   list          List VMs
   list-isos     List available ISOs
   restart       Restart a VM
+  show          Show VM configuration
   start         Start a VM
+  status        Show VM status
   stop          Stop a VM"
 
   cmd::getopt_help "$@"; shift $((OPTIND - 1))
@@ -61,12 +64,15 @@ Commands:
     delete-iso|rmi)   cmd::delete_iso "$@" ;;
     destroy|rm)       cmd::destroy "$@" ;;
     download-iso|dli) cmd::download_iso "$@" ;;
+    edit)             cmd::edit "$@" ;;
     init)             cmd::init "$@" ;;
     list|li)          cmd::list "$@" ;;
     list-isos|lsi)    cmd::list_isos "$@" ;;
     restart|reboot)   cmd::restart "$@" ;;
-    start)            cmd::start "$@" ;;
-    stop)             cmd::stop "$@" ;;
+    show)             cmd::show "$@" ;;
+    start|boot)       cmd::start "$@" ;;
+    status)           cmd::status "$@" ;;
+    stop|shutdown)    cmd::stop "$@" ;;
     *)                cmd::usage "unknown command: ${cmd}" ;;
   esac
 }
@@ -87,7 +93,6 @@ readonly DEFAULT_VLAN=199
 
 # Leave these values alone.
 readonly VM_CONFDIR=/usr/local/etc/bhyve.d
-readonly TAP_NAME_MAX=11
 
 
 ################################################################################
@@ -126,7 +131,11 @@ cmd::getopt_help(){
 
 cmd::console(){
   local usage='console VM'
-  local help='Connect to serial console.'
+  # shellcheck disable=SC2016
+  local help='Connect to serial console.
+Notes:
+  Type ~. to return to your shell.
+  See `man 1 cu` for additional escape codes.'
 
   cmd::getopt_help "$@"; shift $((OPTIND - 1))
 
@@ -136,17 +145,19 @@ cmd::console(){
   vm::exists "$1"  || die "no such vm: ${1}"
   vm::running "$1" || die "vm not running: ${1}"
 
-  cu -l "/dev/nmdm_${1}B" -s 9600
+  exec cu -l "/dev/nmdm_${1}B" -s 9600
 }
 
 cmd::create(){
-  local usage='create [-c CORES] [-m MEM] [-q DATA_QUOTA] [-Q OS_QUOTA] [-v VLANID] NAME [TEMPLATE]'
+  local usage='create [-c CORES] [-i ISO] [-m MEM] [-q DATA_SIZE] [-Q OS_SIZE] [-v VLANID]
+        NAME [TEMPLATE]'
   local help="Create a new VM.
 Options:
   -c CORES       Number of CPU cores
+  -i ISO         Boot from an ISO
   -m MEM         Size of memory (RAM)
-  -q DATA_QUOTA  Size of data disk
-  -Q OS_QUOTA    Size of OS disk
+  -q DATA_SIZE   Size of data disk
+  -Q OS_SIZE     Size of OS disk
   -v VLANID      VLAN ID number"
 
   local \
@@ -155,11 +166,13 @@ Options:
     vm_memory=$DEFAULT_MEMORY \
     vm_os_size=$DEFAULT_OS_SIZE \
     vm_vlan=$DEFAULT_VLAN \
+    vm_iso \
     opt
-  while getopts :c:hm:q:Q:v: opt; do
+  while getopts :c:hi:m:q:Q:v: opt; do
     case $opt in
       c) vm_cpus=$OPTARG ;;
       h) cmd::help ;;
+      i) vm_iso=$OPTARG ;;
       m) vm_memory=$OPTARG ;;
       q) vm_data_size=$OPTARG ;;
       Q) vm_os_size=$OPTARG ;;
@@ -176,6 +189,12 @@ Options:
 
   vm::exists "$name" && die "vm name already in use: ${name}"
 
+  if [ -n "${vm_iso:-}" ]; then
+    iso::exists "$vm_iso" || die "no such iso: ${vm_iso}"
+  fi
+
+  interface::exists "bridge${vm_vlan}" || interface::add_vlan "$vm_vlan"
+
   if [ -n "$template" ]; then
     die unimplemented
   else
@@ -183,9 +202,6 @@ Options:
     zfs create -v -o volmode=dev -V "$vm_os_size"   "${VM_DATASET}/${name}/os"
     zfs create -v -o volmode=dev -V "$vm_data_size" "${VM_DATASET}/${name}/data"
   fi
-
-  local vm_mac
-  interface::derive_mac "$TRUNK_INTERFACE" "$name" vm_mac
 
   cat <<EOF > "${VM_CONFDIR}/${name}.conf"
 name=${name}
@@ -201,8 +217,8 @@ x86.vmexit_on_pause=true
 pci.0.0.0.device=hostbridge
 pci.0.1.0.device=lpc
 pci.0.2.0.device=virtio-net
-pci.0.2.0.backend=tap_$(interface::tap::vm2name "$name")
-pci.0.2.0.mac=${vm_mac}
+pci.0.2.0.backend=$(interface::tap::derive_name "$name")
+pci.0.2.0.mac=$(interface::derive_mac "$TRUNK_INTERFACE" "$name")
 pci.0.3.0.device=nvme
 pci.0.3.0.path=/dev/zvol/${VM_DATASET}/%(name)/os
 pci.0.4.0.device=nvme
@@ -210,6 +226,8 @@ pci.0.4.0.path=/dev/zvol/${VM_DATASET}/%(name)/data
 lpc.com1.path=/dev/nmdm_%(name)A
 vmctl.vlan=${vm_vlan}
 EOF
+
+  vm::start "$name" "${vm_iso:-}"
 }
 
 cmd::delete_iso(){
@@ -283,6 +301,19 @@ cmd::download_iso(){
   fetch -o "${VM_HOME}/isos/${name}.iso" "$url"
 }
 
+cmd::edit(){
+  local usage='edit VM'
+  local help='Edit VM configuration.'
+
+  cmd::getopt_help "$@"; shift $((OPTIND - 1))
+
+  [ $# -lt 1 ] && cmd::usage 'VM not specified'
+  [ $# -gt 1 ] && cmd::usage 'too many arguments'
+
+  vm::exists "$1" || die "no such vm: ${1}"
+  "$EDITOR" "${VM_CONFDIR}/${1}.conf"
+}
+
 cmd::init(){
   local usage='init'
   local help='Initialize bhyve dataset.'
@@ -293,7 +324,7 @@ cmd::init(){
 
   # Create the bhyve parent dataset.
   [ -d "$VM_HOME" ] || zfs create -v -o "mountpoint=${VM_HOME}" "$VM_DATASET"
-  [ -d "${VM_HOME}/isos" ] || zfs create -v "${VM_DATASET}/isos"
+  mkdir -p "${VM_HOME}/isos"
   chmod 700 "$VM_HOME"
 
   # Enable vmm (bhyve) and nmdm (virtual console) kernel modules.
@@ -314,15 +345,40 @@ cmd::list(){
   local usage='list [-t]'
   local help='List configured VMs.'
 
-  cmd::getopt_help "$@"; shift $((OPTIND - 1))
+  local opt terse=false
+  while getopts :th opt; do
+    case $opt in
+      t) terse=true ;;
+      h) cmd::help ;;
+      ?) cmd::usage "unknown option: -${OPTARG}" ;;
+    esac
+  done
+  shift $((OPTIND - 1))
+
   [ $# -eq 0 ] || cmd::usage 'too many arguments'
 
-  for file in "${VM_CONFDIR}"/*.conf; do
-    [ -e "$file" ] || continue
-    name=${file##*/}
-    name=${name%.conf}
-    printf '%s\n' "$name"
-  done
+  local file name status
+  { [ $terse = true ] || echo 'VM STATUS'
+    for file in "${VM_CONFDIR}"/*.conf; do
+      [ -e "$file" ] || continue
+
+      name=${file##*/}
+      name=${name%.conf}
+
+      if [ $terse = true ]; then
+        printf '%s\n' "$name"
+      else
+        if pgrep -qfx "bhyveload .* ${name}"; then
+          status=bootloader
+        elif pgrep -qfx "bhyve: ${name}"; then
+          status=running
+        else
+          status=stopped
+        fi
+        printf '%s %s\n' "$name" "$status"
+      fi
+    done
+  } | column -t
 }
 
 cmd::list_isos(){
@@ -357,6 +413,27 @@ cmd::restart(){
   vm::start "$1"
 }
 
+cmd::show(){
+  local usage='show VM'
+  local help='Show VM configuration.'
+
+  cmd::getopt_help "$@"; shift $((OPTIND - 1))
+
+  [ $# -lt 1 ] && cmd::usage 'VM not specified'
+  [ $# -gt 1 ] && cmd::usage 'too many arguments'
+  local vm=$1
+
+  vm::exists "$vm" || die "no such vm: ${vm}"
+
+  printf -- '------------------------- BHYVE CONFIGURATION -------------------------\n'
+  cat "${VM_CONFDIR}/${vm}.conf"
+  printf -- '\n---------------------------- ZFS DATASET -----------------------------\n'
+  zfs list -o name,used,avail -S name \
+    "${VM_DATASET}/${1}/os" \
+    "${VM_DATASET}/${1}/data"
+}
+
+
 cmd::start(){
   local usage='start [-i ISO] VM'
   local help='Start a VM.
@@ -384,6 +461,37 @@ Options:
   fi
 
   vm::start "$1" "${iso:-}"
+}
+
+cmd::status(){
+  local usage='status VM'
+  local help='Show running VM status.'
+
+  cmd::getopt_help "$@"; shift $((OPTIND - 1))
+
+  [ $# -lt 1 ] && cmd::usage 'VM not specified'
+  [ $# -gt 1 ] && cmd::usage 'too many arguments'
+  local vm=$1
+
+  vm::exists "$vm"  || die "no such vm: ${vm}"
+  vm::running "$vm" || die "vm not running: ${vm}"
+
+  local pid
+  pid=$(vm::pid "$vm")
+
+  printf -- '----------------------------- BHYVE PROCESS ------------------------------\n'
+  ps -auxdr -p "$pid"
+  printf -- '\n---------------------------- ZFS DATASET -----------------------------\n'
+  zfs list -o name,used,avail -S name \
+    "${VM_DATASET}/${1}/os" \
+    "${VM_DATASET}/${1}/data" \
+    | sed "s|^${VM_DATASET}/${vm}/||" \
+    | column -t
+  printf -- '\n--------------------------- RESOURCE USAGE ---------------------------\n'
+  rctl -h -u "process:${pid}" \
+    | grep -E '^(pcpu|memoryuse|vmemoryuse|swapuse|readbps|writebps|readiops|writeiops)=' \
+    | rs -c= -C' ' -T \
+    | column -t
 }
 
 cmd::stop(){
@@ -415,10 +523,22 @@ Options:
 ################################################################################
 # "Library" functions.
 ################################################################################
+interface::add_vlan(){
+  local id=$1
+  ifconfig "vlan${id}" create
+  ifconfig "vlan${id}" vlan "$id" vlandev "$TRUNK_INTERFACE" up
+  ifconfig "bridge${id}" create
+  ifconfig "bridge${id}" addm "vlan${id}" up
+  sysrc -v \
+    "cloned_interfaces+=vlan${id} bridge${id}" \
+    "ifconfig_vlan${id}=vlan ${id} vlandev ${TRUNK_INTERFACE} up" \
+    "ifconfig_bridge${id}=addm vlan${id} up"
+}
+
 interface::derive_mac(){
   # Derive unique mac addresses for an epair interface, based on the physical
   # interface address + vm name.
-  local iface=$1 name=$2 upvar=$3
+  local iface=$1 name=$2
   local hwaddr checksum virtual_mac
 
   # Source: /usr/share/examples/jails/jib
@@ -462,11 +582,15 @@ interface::derive_mac(){
   esac
 
   # => NP:SS:SS:II:II:II
-  setvar "$upvar" "1${virtual_mac}"
+  printf '%s' "1${virtual_mac}"
 }
 
-interface::tap::vm2name(){
-  # Generate an tap(4) interface suffix, based on the vm name.
+interface::exists(){
+  ifconfig "$1" > /dev/null 2>&1
+}
+
+interface::tap::derive_name(){
+  # Generate an tap(4) interface suffix, based on the VM name.
   #
   # The maximum length of a network interface name on FreeBSD is 15 characters.
   # We use a prefix of 'tap_', leaving 11 characters for a unique suffix for each
@@ -475,13 +599,14 @@ interface::tap::vm2name(){
   # If the sanitized vm name is less than 11 characters, we'll simply use it
   # for the suffix. Otherwise, we'll use the last 11 characters of the vm
   # name's SHA-1 hash.
-  local name=$1 tap
-  tap=$(printf '%s' "$name" | tr -dC '[:alnum:]_')
+  local name=$1 sanitized hash
+  sanitized=$(printf '%s' "$name" | tr -dC '[:alnum:]_')
 
-  if [ "${#tap}" -gt "$TAP_NAME_MAX" ]; then
-    printf '%s' "$name" | sha1 | tail -c "$TAP_NAME_MAX"
+  if [ "${#sanitized}" -le 11 ]; then
+    printf 'tap_%s' "$sanitized"
   else
-    printf '%s' "$tap"
+    hash=$(printf '%s' "$name" | sha1 | tail -c 11)
+    printf 'tap_%s' "$hash"
   fi
 }
 
@@ -505,6 +630,12 @@ vm::run(){
   bootdisk=$zvol
   iso_args=''
 
+  # bhyve exit codes:
+  #   0: reboot
+  #   1: shutdown
+  #  >1: error
+  # As long as rc=0, keep rebooting.
+
   while [ "$rc" -eq 0 ]; do
     if [ -n "$iso" ]; then
       # If this is the first boot, or no bootsector exists, boot from ISO.
@@ -525,8 +656,10 @@ vm::run(){
     bhyve -k "${VM_CONFDIR}/${vm}.conf" $iso_args "$vm" && rc=$? || rc=$?
   done
 
+  # If we reach this point, the bhyve process has terminated. Clean up the
+  # /dev/vmm device and tap interface.
   bhyvectl --vm="${vm}" --destroy
-  ifconfig "tap_$(interface::tap::vm2name "$vm")" destroy
+  ifconfig "$(interface::tap::derive_name "$vm")" destroy
 }
 
 vm::running(){
@@ -535,26 +668,31 @@ vm::running(){
 
 vm::stop(){
   local vm=$1 signal=${2:-TERM} pid
-
   pid=$(vm::pid "$vm")
 
   kill -s "$signal" "$pid"
-  while kill -0 "$pid" 2>/dev/null; do
-    sleep 1
-  done
+
+  # Sending bhyve a SIGTERM will initiate an ACPI shutdown. In that case, loop
+  # until the bhyve process exits cleanly.
+  if [ "$signal" = TERM ]; then
+    while kill -0 "$pid" 2>/dev/null; do
+      sleep 1
+    done
+  fi
 }
 
 vm::start(){
-  local vm=$1 iso=${2:-} vlan newif tap_name
+  local vm=$1 iso=${2:-} vlan newif
 
   vlan=$(vm::config::get "$vm" vmctl.vlan)
-  tap_name=$(interface::tap::vm2name "$vm")
 
+  # Create the tap interface.
   newif=$(ifconfig tap create)
   ifconfig "bridge${vlan}" addm "$newif"
-  ifconfig "$newif" name "tap_${tap_name}" descr "vm/${vm}"
+  ifconfig "$newif" name "$(interface::tap::derive_name "$vm")" descr "vm/${vm}"
 
-  vm::run "$vm" "$iso" 2>&1 &
+  # Start the bhyve process in the background.
+  vm::run "$vm" "$iso" > /dev/null 2>&1 &
 }
 
 vm::config::get(){
